#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-airbase
Version  : 78
Release  : 6
URL      : https://github.com/airlift/airbase/archive/78.tar.gz
Source0  : https://github.com/airlift/airbase/archive/78.tar.gz
Source1  : https://repo1.maven.org/maven2/io/airlift/airbase/28/airbase-28.pom
Source2  : https://repo1.maven.org/maven2/io/airlift/airbase/31/airbase-31.pom
Source3  : https://repo1.maven.org/maven2/io/airlift/airbase/56/airbase-56.pom
Source4  : https://repo1.maven.org/maven2/io/airlift/airbase/59/airbase-59.pom
Source5  : https://repo1.maven.org/maven2/io/airlift/airbase/68/airbase-68.pom
Source6  : https://repo1.maven.org/maven2/io/airlift/airbase/72/airbase-72.pom
Source7  : https://repo1.maven.org/maven2/io/airlift/airbase/78/airbase-78.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-airbase-data = %{version}-%{release}
Requires: mvn-airbase-license = %{version}-%{release}

%description
# Airbase
[![Maven Central](https://img.shields.io/maven-central/v/io.airlift/airbase.svg?label=Maven%20Central)](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.airlift%22%20AND%20a%3A%22airbase%22)
[![Build Status](https://travis-ci.org/airlift/airbase.svg?branch=master)](https://travis-ci.org/airlift/airbase)

%package data
Summary: data components for the mvn-airbase package.
Group: Data

%description data
data components for the mvn-airbase package.


%package license
Summary: license components for the mvn-airbase package.
Group: Default

%description license
license components for the mvn-airbase package.


%prep
%setup -q -n airbase-78

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-airbase
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-airbase/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/28
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/28/airbase-28.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/31
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/31/airbase-31.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/56
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/56/airbase-56.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/59
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/59/airbase-59.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/68
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/68/airbase-68.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/72
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/72/airbase-72.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/78
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/io/airlift/airbase/78/airbase-78.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/airlift/airbase/28/airbase-28.pom
/usr/share/java/.m2/repository/io/airlift/airbase/31/airbase-31.pom
/usr/share/java/.m2/repository/io/airlift/airbase/56/airbase-56.pom
/usr/share/java/.m2/repository/io/airlift/airbase/59/airbase-59.pom
/usr/share/java/.m2/repository/io/airlift/airbase/68/airbase-68.pom
/usr/share/java/.m2/repository/io/airlift/airbase/72/airbase-72.pom
/usr/share/java/.m2/repository/io/airlift/airbase/78/airbase-78.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-airbase/LICENSE.txt
